### ISSUE TITLE
Implementation inconsistency

### ISSUE THREAD

**Issue by elyobo** [jmespath/jmespath.js#13]
I had a brief moment of confusion this morning when switching from the ruby library to the javascript library; the search method in the ruby version accepts `(expression, data)` , while the JS version reverses this and takes `(data, expression)`.  Looking at the other implementations, it appears that all of the libraries except for this one accept `(expression, data)`.

I'm not sure that making it consistent is worth the backwards incompatibility, but it's worth noting that this inconsistency exists.

**Comment by jamesls** [comment]
The pattern I've been trying to follow is to model the interface in the language's stdlib's regex library, given it's a pretty similar idea that is, match input data against an expression.  So for python you see `re.search(regex, string)`, so it's `jmespath.search(expr, string)`.

In javascript, I thought I remember an API that had `(data, expression)` which is why I initially chose this ordering of args, but looking through the javascript docs, I actually don't see anything in javascript that uses the `search(data, expression)` pattern so it would be nice to be consistent with other implementations.

I'm with you on this, I'm not sure making it consistent is worth the backwards compatibility.  Let me think about it for a bit...

**Comment by jamesls** [comment]
I'd like to close the loop on this.  After sitting on this for a bit, while it's unfortunate that the inconsistency exists, I don't think it's worth changing at this point in time.

I'm going to suggest this issue is closed out.

**Comment by elyobo** [comment]
Agreed.  I wanted to mention it because it _was_ weird, but the pain of changing it is large and the benefits small.
